name: pfe_smartschool
description: "Smart School Management System - PFE 2026"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+10

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.1

  # UI & Charts
  fl_chart: ^0.66.2
  flutter_local_notifications: ^17.2.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.0

  # Utils
  intl: ^0.19.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
