// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWS13ATaP_0No4yjp6RC-MOiddghSmsc',
    appId: '1:749400575147:web:cd72c7dfed5679e7fdfbee',
    messagingSenderId: '749400575147',
    projectId: 'pfe-smartschool',
    authDomain: 'pfe-smartschool.firebaseapp.com',
    storageBucket: 'pfe-smartschool.firebasestorage.app',
    measurementId: 'G-ZFKB4FNJ6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzCuPF2l3EI6EX1f6frSjPOI8uDBF4uM4',
    appId: '1:749400575147:android:b2ac7b46d99a12f0fdfbee',
    messagingSenderId: '749400575147',
    projectId: 'pfe-smartschool',
    storageBucket: 'pfe-smartschool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFY1DEIp1HawkhF71tZxwC_FwLdKRlSVQ',
    appId: '1:749400575147:ios:0faeee06b32124ddfdfbee',
    messagingSenderId: '749400575147',
    projectId: 'pfe-smartschool',
    storageBucket: 'pfe-smartschool.firebasestorage.app',
    iosBundleId: 'com.example.pfeSmartschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFY1DEIp1HawkhF71tZxwC_FwLdKRlSVQ',
    appId: '1:749400575147:ios:0faeee06b32124ddfdfbee',
    messagingSenderId: '749400575147',
    projectId: 'pfe-smartschool',
    storageBucket: 'pfe-smartschool.firebasestorage.app',
    iosBundleId: 'com.example.pfeSmartschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTWS13ATaP_0No4yjp6RC-MOiddghSmsc',
    appId: '1:749400575147:web:72f4cff894729ec0fdfbee',
    messagingSenderId: '749400575147',
    projectId: 'pfe-smartschool',
    authDomain: 'pfe-smartschool.firebaseapp.com',
    storageBucket: 'pfe-smartschool.firebasestorage.app',
    measurementId: 'G-C4B0K7CQ4S',
  );
}
